
[env]
TERM = "tmux-256color"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "T"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u0017"
key = "D"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "E"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Control"

[terminal.shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux a"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.80

[window.padding]
x = 10
y = 8

[general]
live_config_reload = true
import = ["$XDG_CONFIG_HOME/alacritty/themes/themes/{onedark}.toml"]

[terminal]
